# Build stage
FROM maven:3.8.5-openjdk-17 AS build

WORKDIR /app

# Copy the project file to download dependencies
COPY pom.xml .


# Copy source files
COPY src ./src

# Package the application
RUN mvn clean package -DskipTests

# Run stage
FROM openjdk:17.0.1-jdk-slim

WORKDIR /app

# Copy the jar file from the build stage
COPY --from=build /app/target/studentsystem-0.0.1-SNAPSHOT.jar studentsystem.jar

EXPOSE 8080

# Use array syntax for better signalling and potential variable expansion
ENTRYPOINT ["java", "-jar", "studentsystem.jar"]